packages:
  - "apps/mobile"
  - "packages/language-packs"
  - "packages/language-core-ts"

minimumReleaseAgeExclude:
  - expo-constants@57.0.20
  - expo-modules-core@57.0.20
  - expo@57.0.26

virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 20
