// Lossless frames of theme-shigure.gif for Android mask rendering.
export const themeMaskFrames = [
  require('../../assets/theme-mask/frame-00.png'),
  require('../../assets/theme-mask/frame-01.png'),
  require('../../assets/theme-mask/frame-02.png'),
  require('../../assets/theme-mask/frame-03.png'),
  require('../../assets/theme-mask/frame-04.png'),
  require('../../assets/theme-mask/frame-05.png'),
  require('../../assets/theme-mask/frame-06.png'),
  require('../../assets/theme-mask/frame-07.png'),
  require('../../assets/theme-mask/frame-08.png'),
  require('../../assets/theme-mask/frame-09.png'),
  require('../../assets/theme-mask/frame-10.png'),
  require('../../assets/theme-mask/frame-11.png'),
  require('../../assets/theme-mask/frame-12.png'),
  require('../../assets/theme-mask/frame-13.png'),
  require('../../assets/theme-mask/frame-14.png'),
  require('../../assets/theme-mask/frame-15.png'),
  require('../../assets/theme-mask/frame-16.png'),
  require('../../assets/theme-mask/frame-17.png'),
  require('../../assets/theme-mask/frame-18.png'),
  require('../../assets/theme-mask/frame-19.png'),
  require('../../assets/theme-mask/frame-20.png'),
  require('../../assets/theme-mask/frame-21.png'),
  require('../../assets/theme-mask/frame-22.png'),
  require('../../assets/theme-mask/frame-23.png'),
  require('../../assets/theme-mask/frame-24.png'),
  require('../../assets/theme-mask/frame-25.png'),
  require('../../assets/theme-mask/frame-26.png'),
  require('../../assets/theme-mask/frame-27.png'),
  require('../../assets/theme-mask/frame-28.png'),
  require('../../assets/theme-mask/frame-29.png'),
  require('../../assets/theme-mask/frame-30.png'),
] as const;
